### ISSUE TITLE
Actionbar Android

### ISSUE THREAD

**Issue by jwktje** [raulduran/VideoPlayer#4]
The plugin works great! I love it. It does show a quick flash of the action bar in android after it loads a video. Would it be possible to hide the action bar somehow?

**Comment by raulduran** [comment]
Right now it's not possible as it plays the video natively app depending on the default device. The solution could be to create an activity with a custom player and instead of calling the Intent of the video call that activity.

**Comment by jwktje** [comment]
Would it also be possible to use the videoView in Android? I only need it to prevent the actionbar in Android.
